name: Update README table of contents

on:
  push:
    branches:
    - folderwise
    - master
    paths:
    - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Update TOC
      run: npx markdown-toc README.md -i
    - name: Delete branch
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{github.token}}
        branches: folderwise2
    - name: Commit and push if README changed
      run: |-
        git config --global user.email "readme-bot@example.com"
        git config --global user.name "README-bot"
        git checkout folderwise2
        git push --set-upstream origin folderwise2
        git pull folderwise2
        mv .folderwise_organization/extract.py .
        python extract.py
        rm extract.py
        git add -A || git commit -a -m "Update folderwise"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
