name: Update README table of contents

on:
  push:
    branches:
    - folderwise
    - master
    paths:
    - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Update TOC
      run: npx markdown-toc README.md -i
    - name: Commit and push if README changed
      run: |-
        git config --global user.email "readme-bot@example.com"
        git config --global user.name "README-bot"
        git push --set-upstream origin folderwise2
        os.system('rm *.md')
        git branch folderwise2
        mv .folderwise_organization/extract.py
        python extract.py
        git add -A || git commit -a -m "Update folderwise"
        git push

